Order fixing on custom questions
codalab/chagrade pull request #131
Opened 2020-04-21 17:14 UTC by brendon-lind

Reversed questions on the student submission view.

# Known issues to be addressed in a separate PR
Resolves #120 

# Checklist
- [x] Code review by me 
- [x] Hand tested by me 
- [x] I'm proud of my work
- [ ] Code review by reviewer
- [ ] Hand tested by reviewer
- [ ] Ready to merge

2020-04-21 17:19 UTC, gibsonbailey requested changes

2020-04-21 17:19 UTC, gibsonbailey commented on static/riotjs/student/submit_homework.tag
> +                    console.info("data", data)
Remove `console.info`

2020-04-21 18:21 UTC, brendon-lind commented on static/riotjs/student/submit_homework.tag
> +                    console.info("data", data)
My bad. Removed.

2020-04-23 07:49 UTC, gibsonbailey commented
Can we ensure that questions appear in the same order on the homework definition form as the student submission form? This way, instructors can at least be aware of the order that will be presented to students, as it's usually important.

2020-04-23 15:26 UTC, brendon-lind commented
It seems like it is working properly on this branch. Must have been something buggy on another branch before this fix.

2020-04-24 16:24 UTC, merged