First draft of integration tests for chagrade - Testing get/post/put/…
codalab/chagrade pull request #31
Opened 2018-12-23 21:33 UTC by ReproKillbot

…delete with instructor/authenticated/anonymous users. Some issues exist with Auth'd and Instructor users:

Cannot pass in Users/Submitted_homeworks for student post/put tests.  

Unsure of what to pass in for "competition_urls" for submissions post/put test.  

Cannot pass in "members" into the teams post test.

2018-12-23 21:36 UTC, ckcollab commented on apps/api/tests/test_anonymous_permissions.py
> +        resp = self.client.put(path=reverse('api:chauser-detail', kwargs={'version': 'v1', 'pk': self.student_user.pk}),
Please indent on the following line if you're doing more arguments, like this:

```python
something = something(
    kw_arg=a_thing,
    other_arg=something_else,
    ...
)```

2018-12-23 21:37 UTC, ckcollab commented on apps/api/tests/test_anonymous_permissions.py
> +    @tag('passing')
please remove these tags ???

2018-12-23 21:37 UTC, ckcollab commented on apps/api/tests/test_anonymous_permissions.py
> +        #  Tests that we can't retrieve a list of criteria
Please remove all extraneous comments

2018-12-23 21:37 UTC, ckcollab commented on apps/api/tests/test_authenticated_permissions.py
> +        # assert self.student.student_id == 'test_id_123'
pull cruft?

2019-01-10 01:01 UTC, ckcollab requested changes

2019-01-10 01:01 UTC, ckcollab commented on apps/api/tests/test_submission.py
> +    def test_instructor_user_can_only_perform_get_and_post_methods_on_submissions(self):
why test authenticated user + instructor for this? aren't they kinda the same?

2019-01-10 01:01 UTC, ckcollab commented on requirements.txt
> +responses
please put a version # here, these all need version #'s actually

2019-01-10 19:48 UTC, ckcollab commented on apps/api/tests/test_definitions.py
> +            data={'klass': self.klass.pk,
indentation

2019-01-10 19:48 UTC, ckcollab commented on apps/api/tests/test_definitions.py
> +        resp = self.client.get(path=reverse(
indentation

2019-01-10 19:48 UTC, ckcollab commented on apps/api/tests/test_grades.py
> +            data={"submission": '',
indentation

2019-01-10 19:48 UTC, ckcollab commented on apps/api/tests/test_grades.py
> +        resp = self.client.get(path=reverse(
indentation

2019-01-10 19:49 UTC, ckcollab commented on apps/api/tests/test_grades.py
> +        resp = self.client.get(path=reverse(
actually, this doesn't even need to be multiple lines...

2019-01-10 19:49 UTC, ckcollab commented on apps/api/tests/test_grades.py
> +        resp = self.client.get(path=reverse(
```resp = self.client.get(path=reverse('api:grade-list', kwargs={'version': 'v1'}))```

Please put on one line so it's easy to read

2019-01-10 19:50 UTC, ckcollab commented on apps/api/tests/test_grades.py
> +            data={"submission": self.submission.pk,
indentation

2019-01-10 19:50 UTC, ckcollab commented on apps/api/tests/test_grades.py
> +        resp = self.client.get(path=reverse(
put on single line

2019-01-16 22:25 UTC, Tthomas63 commented on apps/api/tests/test_submission.py
> +        responses.add(
We should pass the sub_id instead of just a static ID of 2:

```'http://0.0.0.0/api/v1/submissions/{}/'.format(sub_id)```

2019-01-16 22:25 UTC, Tthomas63 commented on apps/api/tests/test_submission.py
> +                'id': 'https://github.com/Tthomas63/chagrade_test_submission',
I believe the `id` value of responses from v1.5 API should look like: ```competition/15595/submission/44798/4aba772a-a6c1-4e6f-a82b-fb9d23193cb6.zip```

So post_submission can split it up like this for the file-name:
```
    submission_data = resp.json()['id']
    submission_data_split = submission_data.split('/')
    submission_file_name = submission_data_split[-1]
    s3_file_url = resp.json()['url']
```

Also the `url` value is usually an s3 storage link, but these are both probably fine.

2019-01-16 22:25 UTC, Tthomas63 commented on apps/api/tests/test_submission.py
> +        responses.add(
Why use the same URL for mocking storage/github?

2019-01-16 22:25 UTC, Tthomas63 commented on apps/api/tests/test_submission.py
> +                "question_answers": ''
We should probably just not pass these instead of passing an empty string. If you're getting errors it is required, just set `required=False` on the serializer.

2019-01-16 22:25 UTC, Tthomas63 commented on apps/api/tests/test_teams.py
> +        resp = self.client.post(
Students should not be able to post to the `teams` endpoint

2019-01-16 22:25 UTC, Tthomas63 commented on apps/api/tests/test_teams.py
> +        resp = self.client.put(
Instructor should be able to use all methods on this endpoint.

2019-01-16 22:25 UTC, Tthomas63 commented on apps/api/tests/test_submission.py
> +    def test_student_can_perform_crud_methods_on_submissions(self):
See comments below on mocked responses.

2019-01-16 22:25 UTC, Tthomas63 commented on apps/api/tests/test_grades.py
> +        resp = self.client.post(
Student User should not be able to post grades.

2019-01-16 22:25 UTC, Tthomas63 commented on apps/api/tests/test_criterias.py
> +
Is there a specific reason we stopped testing methods that should not work? (Post/Delete)

2019-01-21 18:48 UTC, merged